### ISSUE TITLE
Import eslint rules from web project

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-server#61]
## Requirements

- Discuss eslint rules together as a team. 
- Import web project eslint rules if acceptable.

**Comment by ann-kilzer** [comment]
Can we say "true up" the eslint rules between the two projects? I quite like `airbhb` because it's a 3rd party style, tried and trusted sheet rather than a personal style sheet of @ermish. I understand that this message carries some emotional things and revisits a disagreement from months ago, so happy to jump on a call to talk things out.

My vote would be start with `airbnb` and add exceptions as needed.

And recognize that reformatting either codebase will have a short term slowing effect of development. The backend development is very active right now.

**Comment by ermish** [comment]
yeah let's chat through this one on a call!
 I definitely have some thoughts on the topic and a fair distaste for the airbnb styles now. We always ended up removing from every project because we made so many overrides that it was hurting more than helping.

**Comment by ann-kilzer** [comment]
Much appreciated! Maybe you can talk through your reasoning behind the choices and I can also explain my thoughts on colors afterwards 😅 At the end we just need a linting decision to be made so we can move forward

**Comment by ann-kilzer** [comment]
Okay we could get rid of airbnb given it has some weird stuff, but reading through the web .eslintrc.js right now and some things should not be ported over:

1. Magic numbers 1, 2, 3 instead of 'off' / 'warn' / 'error'
2. Turning off `eqeqeq`
3. Turning off `no-param-reassign` 
4. Anything related to vue
5. linebreak-style not keen on invisible carriage returns showing up in the code. This was causing trouble with Netlify the other day
6. Maxlen of 200 should be 100-120 for friendliness to people on laptops

And some that I am unsure about:
1. no-useless-escape could be a warn
2. I'm partial to semicolons for safety

I'm going through a list of 100 lint rules right now and I don't think it's the best use of our time to debate each one... hence why I like taking a community standard and deviating from it slightly

**Comment by ann-kilzer** [comment]
I'll make a PR of what I am okay with bringing into the backend and let's see if we can move forward from there.
