### ISSUE TITLE
Prisma ARM error

### ISSUE THREAD

**Issue by theyokohamalife** [ourjapanlife/findadoc-server#90]
We noticed an error when running `docker compose up` on an ARM / M1 mac.

## Error Message

```
 Environment variables loaded from .env
findadoc-server-migrate-1       | Error: Unable to establish a connection to query-engine-node-api library. It seems that the current architecture arm64 is not supported, or that libc is missing from the system.
findadoc-server-migrate-1       | Details: Unable to require(`/target/node_modules/@prisma/engines/libquery_engine-linux-arm64-openssl-3.0.x.so.node`)
findadoc-server-migrate-1       |  Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /target/node_modules/@prisma/engines/libquery_engine-linux-arm64-openssl-3.0.x.so.node)
findadoc-server-migrate-1       | [Context: getDmmf]
```

**Comment by ann-kilzer** [comment]
@theyokohamalife please ask for support in https://slack.prisma.io/ or perhaps someone else with an M1 mac can help you debug this ☹️

**Comment by ermish** [comment]
I just tried to see if I could help figure out the ARM issue and it also doesn't run on windows 😿
I believe it's because of the
`command: "sh -c 'until [[ -f /in/db-init-done && -d /target/node_modules ]]; do sleep 1; done; yarn migrate; yarn prisma db seed'"` and the `db-init.sh` 
scripts that are running outside the linux-based docker image.

We should avoid using `.sh` scripts outside of docker where possible as they don't run natively on windows (😑) and have different commands between linux and mac
My recommendation would be to wrap the base postrgres docker image and move all of our setup scripts within.

**Comment by ann-kilzer** [comment]
To summarize the discussion @ermish and I had:

1. The shell script issue looks orthogonal and has been moved to #91 
2. The schema.prisma configuration here was an attempt to address this issue: https://github.com/ourjapanlife/findadoc-server/blob/main/prisma/schema.prisma#L6
3. Getting the server running in docker may mitigate this

**Comment by theyokohamalife** [comment]
Linux users have reported that changing node from `alpine` to `lts` worked for them. [Source](https://github.com/prisma/prisma/issues/9572#issuecomment-933020243)

**Comment by ann-kilzer** [comment]
@theyokohamalife I found a much more current thread on this issue here: https://github.com/prisma/prisma/issues/8478

Let's watch the discussion and you may wish to try [this comment](https://github.com/prisma/prisma/issues/8478#issuecomment-1355209706)
